[package]
name = "range-split"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
bytesize = "1.3.0"
clap = { version = "4.5.21", features = ["derive"] }
rand = "0.8.5"
rangetools = "0.1.4"
thiserror = "2.0.3"
