[package]
name = "elevation"
version = "0.1.0"
authors = ["Wayne Van Son"]
edition = "2021"

[dependencies]
axum = "0.7.4"
clap = { version = "4.4.18", features = ["derive"] }
osmpbf = "0.3.3"
serde = { version = "1.0.195", features = ["derive"] }
tokio = { version = "1.35.1", features = ["full"] }
