[package]
name = "elevation"
version = "0.1.0"
authors = ["Wayne Van Son"]
edition = "2021"

[dependencies]
moka = { version = "0.12.8", features = ["sync"] }
axum = { version = "0.7.4", features = ["macros"] }
axum-extra = { version = "0.9.2", features = ["query"] }
clap = { version = "4.4.18", features = ["derive"] }
derive_more = "0.99.17"
futures = "0.3.30"
geo = { version = "0.27.0", features = ["serde"] }
indexmap = "2.1.0"
indexset = "0.3.6"
itertools = "0.12.0"
len-trait = { version = "0.6.1", features = ["nightly"] }
ordered-float = { version = "4.3.0", features = ["serde", "num-cmp"] }
osmpbf = "0.3.3"
petgraph = { version = "0.6.5", default-features = false, features = [
    "graphmap",
    "rayon",
] }
redis = "0.27.4"
reqwest = { version = "0.11.23", features = ["json"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
thiserror = "1.0.64"
tokio = { version = "1.35.1", features = ["full"] }
url = { version = "2.5.0", features = ["serde"] }
rayon = "1.10.0"

[profile.test]
opt-level = 3
