[package]
name = "elevation"
version = "0.1.0"
authors = ["Wayne Van Son"]
edition = "2021"

[dependencies]
axum = "0.7.4"
clap = { version = "4.4.18", features = ["derive"] }
derive_more = "0.99.17"
futures = "0.3.30"
geo = { version = "0.27.0", features = ["serde"] }
indexmap = "2.1.0"
indexset = "0.3.6"
itertools = "0.12.0"
osmpbf = "0.3.3"
petgraph = { version = "0.6.4", default-features = false, features = [
    "graphmap",
] }
reqwest = { version = "0.11.23", features = ["json"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
tokio = { version = "1.35.1", features = ["full"] }

[profile.test]
opt-level = 3
