services:
  backend:
    build:
      target: backend-production
    ports:
      - 3000:3000
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
