services:
  backend:
    restart: always
    depends_on:
      - database
      - open-elevation
    build:
      target: server
    volumes:
      - ./:/app
      - backend-planet-osm-pbf:/data
    ports:
      - 3000:3000

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - postgres-database:/var/lib/postgres/data

  adminer:
    depends_on:
      - database
    image: adminer
    restart: always
    ports:
      - 8080:8080

  open-elevation:
    image: ghcr.io/waynevanson/open-elevation:main
    volumes:
      - open-elevation-data:/data/tiles
    ports:
      - 9000:8080

volumes:
  backend-planet-osm-pbf:
  postgres-database:
  open-elevation-data:

