services:
  backend:
    restart: always
    depends_on:
      - open-elevation
    build:
      target: server
    volumes:
      - ./:/app
      - backend-planet-osm-pbf:/data
    ports:
      - 3000:3000

  open-elevation:
    image: ghcr.io/waynevanson/open-elevation:main
    volumes:
      - open-elevation-data:/data
    ports:
      - 9000:8080
    environment:
      - PYTHONUNBUFFERED=1
    command: stdbuf -i0 -o0 -e0 python3 server.py

volumes:
  backend-planet-osm-pbf:
  open-elevation-data:
