services:
  database:
    image: postgres:alpine
    ports:
      - 54321:5432
  open-elevation:
    build:
      dockerfile: images/elevation/Dockerfile
      context: .
    volumes:
      - images/elevation/data:/data
    ports:
      - 9000:8080
    environment:
      - PYTHONUNBUFFERED=1
    

    