services:
  backend:
    restart: always
    depends_on:
      - open-elevation
      - redis
    build:
      target: server
    volumes:
      - ./:/app
      - backend-planet-osm-pbf:/data
    ports:
      - 3000:3000

  redis:
    image: redis:latest-alpine
    ports:
      - 6379:6379

  open-elevation:
    build:
      dockerfile: images/elevation/Dockerfile
      context: .
    volumes:
      - open-elevation-data:/data
    ports:
      - 9000:8080
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  backend-planet-osm-pbf:
  open-elevation-data:
